from typing import Protocol, runtime_checkable

from domain.code_entities import CodeScanRecord
from domain.entities import CVEException, ScanRecord


@runtime_checkable
class RepositoryPort(Protocol):
    @property
    def is_available(self) -> bool: ...

    async def save_scan(self, record: ScanRecord) -> None: ...

    async def get_history(
        self, image_name: str, limit: int = 20
    ) -> list[ScanRecord]: ...

    async def get_all_recent(self, limit: int = 50) -> list[ScanRecord]: ...

    async def get_active_exceptions(self) -> list[CVEException]: ...

    async def add_exception(self, exc: CVEException) -> None: ...

    async def delete_exception(self, cve_id: str) -> None: ...

    async def save_code_scan(self, record: CodeScanRecord) -> None: ...

    async def get_code_history(
        self, project_name: str, limit: int = 20
    ) -> list[CodeScanRecord]: ...

    async def get_all_recent_code_scans(self, limit: int = 50) -> list[CodeScanRecord]: ...
